if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    target_compile_definitions(demoapp PUBLIC "PLATFORM_LINUX")
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    target_compile_definitions(demoapp PUBLIC "PLATFORM_MACOS")
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    target_compile_definitions(demoapp PUBLIC "PLATFORM_WINDOWS")
endif()